import { describe, expect, it } from "vitest";
import { buildHeader, compose } from "../src/compose.js";

describe("compose", () => {
  it("replaces include markers with central partials", () => {
    const result = compose({
      skeleton: "# Title\n\n<!-- include: CODING.md -->\n\n<!-- include: TESTING.md -->\n",
      centralPartials: { CODING: "## Coding\n\n- rule", TESTING: "## Testing\n\n- rule" },
      customPartials: {},
      skip: [],
    });
    expect(result.agentsMd).toContain("## Coding");
    expect(result.agentsMd).toContain("## Testing");
    expect(result.included).toEqual(["CODING", "TESTING"]);
    expect(result.missing).toEqual([]);
  });

  it("prepends CUSTOM content before central content", () => {
    const result = compose({
      skeleton: "<!-- include: CODING.md -->\n",
      centralPartials: { CODING: "## Coding\n\n- central rule" },
      customPartials: { CODING: "- repo-specific rule" },
      skip: [],
    });
    expect(result.agentsMd).toContain("- central rule");
    expect(result.agentsMd).toContain("- repo-specific rule");
    expect(result.agentsMd.indexOf("- repo-specific rule")).toBeLessThan(
      result.agentsMd.indexOf("- central rule"),
    );
    expect(result.withCustom).toEqual(["CODING"]);
  });

  it("ignores empty CUSTOM files", () => {
    const result = compose({
      skeleton: "<!-- include: CODING.md -->\n",
      centralPartials: { CODING: "## Coding" },
      customPartials: { CODING: "   \n\n  " },
      skip: [],
    });
    expect(result.withCustom).toEqual([]);
  });

  it("omits skipped sections and tracks them", () => {
    const result = compose({
      skeleton: "<!-- include: CODING.md -->\n<!-- include: TESTING.md -->\n",
      centralPartials: { CODING: "## Coding", TESTING: "## Testing" },
      customPartials: {},
      skip: ["TESTING"],
    });
    expect(result.agentsMd).toContain("## Coding");
    expect(result.agentsMd).not.toContain("## Testing");
    expect(result.included).toEqual(["CODING"]);
    expect(result.skipped).toEqual(["TESTING"]);
  });

  it("uses a custom partial when the central one is absent", () => {
    const result = compose({
      skeleton: "<!-- include: PROJECT.md -->\n",
      centralPartials: {},
      customPartials: { PROJECT: "## Project\n\nPer-repo description." },
      skip: [],
    });
    expect(result.agentsMd).toContain("Per-repo description.");
    expect(result.missing).toEqual([]);
    expect(result.included).toEqual(["PROJECT"]);
    expect(result.withCustom).toEqual(["PROJECT"]);
  });

  it("reports a partial missing when neither central nor custom provides it", () => {
    const result = compose({
      skeleton: "<!-- include: PROJECT.md -->\n",
      centralPartials: {},
      customPartials: {},
      skip: [],
    });
    expect(result.missing).toEqual(["PROJECT"]);
  });

  it("reports missing partials without throwing", () => {
    const result = compose({
      skeleton: "<!-- include: NOPE.md -->",
      centralPartials: {},
      customPartials: {},
      skip: [],
    });
    expect(result.missing).toEqual(["NOPE"]);
  });

  it("prepends a header when provided", () => {
    const header = buildHeader("TOOLING/agents-md-templates");
    const result = compose({
      skeleton: "# Title\n",
      centralPartials: {},
      customPartials: {},
      skip: [],
      header,
    });
    expect(result.agentsMd.startsWith("<!-- Generated by agents-md-sync")).toBe(true);
    expect(result.agentsMd).toContain("TOOLING/agents-md-templates");
    expect(result.agentsMd).not.toContain("@");
  });
});
