import { describe, expect, it } from "vitest";
import { buildCommitMessage, buildPrDescription } from "../src/drift.js";

const LABEL = "TOOLING/agents-md-templates";

describe("buildPrDescription", () => {
  it("includes the template label and section of included partials", () => {
    const desc = buildPrDescription({
      templateRepoLabel: LABEL,
      included: ["CODING", "TESTING"],
      skipped: [],
      withCustom: [],
    });
    expect(desc).toContain(`Generated by \`agents-md-sync\` from \`${LABEL}\`.`);
    expect(desc).toContain("## Partials");
    expect(desc).toContain("- Included: `CODING`, `TESTING`");
  });

  it("lists skipped and with-custom sections when present", () => {
    const desc = buildPrDescription({
      templateRepoLabel: LABEL,
      included: ["CODING"],
      skipped: ["TESTING"],
      withCustom: ["CODING"],
    });
    expect(desc).toContain("- Skipped: `TESTING`");
    expect(desc).toContain("- With local addendum: `CODING`");
  });

  it("omits empty partials sub-sections", () => {
    const desc = buildPrDescription({
      templateRepoLabel: LABEL,
      included: [],
      skipped: [],
      withCustom: [],
    });
    expect(desc).not.toContain("- Included");
    expect(desc).not.toContain("- Skipped");
    expect(desc).not.toContain("- With local addendum");
  });

  it("does not mention drift, last sync, or a trailer", () => {
    const desc = buildPrDescription({
      templateRepoLabel: LABEL,
      included: ["CODING"],
      skipped: [],
      withCustom: [],
    });
    expect(desc).not.toContain("Drift");
    expect(desc).not.toContain("No prior sync");
    expect(desc).not.toContain("X-AgentsMd-Sync-Source");
  });
});

describe("buildCommitMessage", () => {
  it("has a conventional subject and a short body naming the template", () => {
    const msg = buildCommitMessage(LABEL);
    expect(msg.startsWith("chore: update AGENTS.md")).toBe(true);
    expect(msg).toContain(`Generated by agents-md-sync from ${LABEL}.`);
    expect(msg).not.toContain("X-AgentsMd-Sync-Source");
    expect(msg).not.toContain("@");
  });
});
