export interface ComposeInput {
  skeleton: string;
  centralPartials: Record<string, string>;
  customPartials: Record<string, string>;
  skip: string[];
  header?: string;
}

export type PartialSource = "central" | "custom" | "both";
export type PartialStatus = "included" | "skipped" | "missing";

export interface PartialEntry {
  name: string;
  status: PartialStatus;
  source?: PartialSource;
  centralBytes?: number;
  customBytes?: number;
}

export interface ComposeResult {
  agentsMd: string;
  included: string[];
  skipped: string[];
  withCustom: string[];
  missing: string[];
  sources: Record<string, PartialSource>;
  order: PartialEntry[];
}

const INCLUDE_RE = /<!--\s*include:\s*([A-Za-z0-9_-]+)\.md\s*-->/g;

export function compose(input: ComposeInput): ComposeResult {
  const skipSet = new Set(input.skip);
  const included: string[] = [];
  const skipped: string[] = [];
  const withCustom: string[] = [];
  const missing: string[] = [];
  const sources: Record<string, PartialSource> = {};
  const order: PartialEntry[] = [];

  const body = input.skeleton.replace(INCLUDE_RE, (_match, rawName: string) => {
    const name = rawName;
    if (skipSet.has(name)) {
      skipped.push(name);
      order.push({ name, status: "skipped" });
      return "";
    }
    const central = input.centralPartials[name];
    const customRaw = input.customPartials[name];
    const custom = customRaw !== undefined && customRaw.trim().length > 0 ? customRaw : undefined;
    if (central === undefined && custom === undefined) {
      missing.push(name);
      order.push({ name, status: "missing" });
      return `<!-- MISSING PARTIAL: ${name}.md -->`;
    }
    included.push(name);
    if (custom !== undefined) withCustom.push(name);
    const source: PartialSource =
      central !== undefined && custom !== undefined ? "both" : custom !== undefined ? "custom" : "central";
    sources[name] = source;
    order.push({
      name,
      status: "included",
      source,
      centralBytes: central !== undefined ? byteLen(central) : undefined,
      customBytes: custom !== undefined ? byteLen(custom) : undefined,
    });
    if (central === undefined) return (custom as string).trimEnd();
    if (custom !== undefined) return `${custom.trimEnd()}\n\n${central.trimEnd()}`;
    return central.trimEnd();
  });

  const cleaned = collapseBlankRuns(body);
  const header = input.header ? input.header.trimEnd() + "\n\n" : "";
  const agentsMd = header + cleaned.trimEnd() + "\n";

  return { agentsMd, included, skipped, withCustom, missing, sources, order };
}

function byteLen(s: string): number {
  return Buffer.byteLength(s, "utf8");
}

function collapseBlankRuns(text: string): string {
  return text.replace(/\n{3,}/g, "\n\n");
}

export function buildHeader(templateRepo: string): string {
  return `<!-- Generated by agents-md-sync from ${templateRepo}. Edit via .agents/*.md; do not edit this file directly. -->`;
}
