export interface ComposeInput {
  skeleton: string;
  centralPartials: Record<string, string>;
  customPartials: Record<string, string>;
  skip: string[];
  header?: string;
}

export interface ComposeResult {
  agentsMd: string;
  included: string[];
  skipped: string[];
  withCustom: string[];
  missing: string[];
}

const INCLUDE_RE = /<!--\s*include:\s*([A-Za-z0-9_-]+)\.md\s*-->/g;

export function compose(input: ComposeInput): ComposeResult {
  const skipSet = new Set(input.skip);
  const included: string[] = [];
  const skipped: string[] = [];
  const withCustom: string[] = [];
  const missing: string[] = [];

  const body = input.skeleton.replace(INCLUDE_RE, (_match, rawName: string) => {
    const name = rawName;
    if (skipSet.has(name)) {
      skipped.push(name);
      return "";
    }
    const central = input.centralPartials[name];
    if (central === undefined) {
      missing.push(name);
      return `<!-- MISSING PARTIAL: ${name}.md -->`;
    }
    included.push(name);
    const custom = input.customPartials[name];
    if (custom !== undefined && custom.trim().length > 0) {
      withCustom.push(name);
      return `${custom.trimEnd()}\n\n${central.trimEnd()}`;
    }
    return central.trimEnd();
  });

  const cleaned = collapseBlankRuns(body);
  const header = input.header ? input.header.trimEnd() + "\n\n" : "";
  const agentsMd = header + cleaned.trimEnd() + "\n";

  return { agentsMd, included, skipped, withCustom, missing };
}

function collapseBlankRuns(text: string): string {
  return text.replace(/\n{3,}/g, "\n\n");
}

export function buildHeader(templateRepo: string, sha: string): string {
  return `<!-- Generated by agents-md-sync from ${templateRepo}@${sha}. Edit via .agents/*.md; do not edit this file directly. -->`;
}
