export const SYNC_TRAILER_PREFIX = "X-AgentsMd-Sync-Source:";

export interface CommitInfo {
  id: string;
  message: string;
  authorTimestamp: number;
}

export interface DriftInput {
  templateRepoLabel: string;
  centralSha: string;
  lastSyncSha: string | null;
  upstreamCommitsSinceLastSync: CommitInfo[];
  included: string[];
  skipped: string[];
  withCustom: string[];
}

export function extractLastSyncSha(commits: CommitInfo[], templateRepoLabel: string): string | null {
  for (const commit of commits) {
    const trailer = findTrailer(commit.message, templateRepoLabel);
    if (trailer) return trailer;
  }
  return null;
}

function findTrailer(message: string, templateRepoLabel: string): string | null {
  const lines = message.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed.startsWith(SYNC_TRAILER_PREFIX)) continue;
    const value = trimmed.slice(SYNC_TRAILER_PREFIX.length).trim();
    const [repo, sha] = value.split("@");
    if (repo === templateRepoLabel && sha) return sha;
  }
  return null;
}

export function buildPrDescription(input: DriftInput): string {
  const lines: string[] = [];
  lines.push(`Generated by \`agents-md-sync\` from \`${input.templateRepoLabel}@${input.centralSha}\`.`);
  lines.push("");
  lines.push("## Partials");
  if (input.included.length > 0) {
    lines.push(`- Included: ${input.included.map(backtick).join(", ")}`);
  }
  if (input.skipped.length > 0) {
    lines.push(`- Skipped: ${input.skipped.map(backtick).join(", ")}`);
  }
  if (input.withCustom.length > 0) {
    lines.push(`- With local addendum: ${input.withCustom.map(backtick).join(", ")}`);
  }
  lines.push("");
  lines.push("## Drift since last sync");
  if (!input.lastSyncSha) {
    lines.push("_No prior sync found on this repo. This is the first agents-md-sync-generated PR._");
  } else if (input.upstreamCommitsSinceLastSync.length === 0) {
    lines.push(`_No upstream changes in central partials since \`${input.lastSyncSha}\`._`);
  } else {
    lines.push(`Upstream commits since \`${input.lastSyncSha}\`:`);
    lines.push("");
    for (const c of input.upstreamCommitsSinceLastSync) {
      const first = c.message.split(/\r?\n/)[0] ?? "";
      lines.push(`- \`${c.id.slice(0, 10)}\` ${first}`);
    }
  }
  lines.push("");
  lines.push("---");
  lines.push(`${SYNC_TRAILER_PREFIX} ${input.templateRepoLabel}@${input.centralSha}`);
  return lines.join("\n");
}

export function buildCommitMessage(templateRepoLabel: string, centralSha: string): string {
  return [
    "chore: update AGENTS.md",
    "",
    "Generated by agents-md-sync.",
    "",
    `${SYNC_TRAILER_PREFIX} ${templateRepoLabel}@${centralSha}`,
  ].join("\n");
}

function backtick(s: string): string {
  return `\`${s}\``;
}
