export interface DriftInput {
  templateRepoLabel: string;
  included: string[];
  skipped: string[];
  withCustom: string[];
}

export function buildPrDescription(input: DriftInput): string {
  const lines: string[] = [];
  lines.push(`Generated by \`agents-md-sync\` from \`${input.templateRepoLabel}\`.`);
  lines.push("");
  lines.push("## Partials");
  if (input.included.length > 0) {
    lines.push(`- Included: ${input.included.map(backtick).join(", ")}`);
  }
  if (input.skipped.length > 0) {
    lines.push(`- Skipped: ${input.skipped.map(backtick).join(", ")}`);
  }
  if (input.withCustom.length > 0) {
    lines.push(`- With local addendum: ${input.withCustom.map(backtick).join(", ")}`);
  }
  return lines.join("\n");
}

export function buildCommitMessage(templateRepoLabel: string): string {
  return [
    "chore: update AGENTS.md",
    "",
    `Generated by agents-md-sync from ${templateRepoLabel}.`,
  ].join("\n");
}

function backtick(s: string): string {
  return `\`${s}\``;
}
